tox.ini

I keep my virtualenvs in a 'sandbox' subdirectory of the working directory.  Without this change, tox has pep8 and pytest recurse into that directory and run a lot of (failing) tests for installed packages.  This shouldn't hurt elsewhere.

ignore 'sandbox' too

---

cloudtools/scripts/aws_deploy_stack.py
configs/cloudformation/README.md
configs/cloudformation/network.py
configs/cloudformation/stacks.yml
conftest.py
setup.py

This defines the releng network and is currently deployed as it appears in this patch.
There's an AWS bug around customer gateways that means this stack will "steal" the existing CGW if the IP and ASN match.  So I've faked them out for the moment.  Wen we're ready to deploy, I'll reset those to their proper values, delete the existing customer gateway, and update this stack (or re-create if there's some other bug).  Once that's done, I'll move nagios1 to the appropriate new subnet, and the delete all the old cruft.  And we'll be deploy'd!

Bug 1116271: Manage the Releng Network in us-west-2

---

cloudtools/scripts/aws_deploy_stack.py
cloudtools/tests/test_scripts_aws_deploy_stack.py
configs/cloudformation/README.md
configs/cloudformation/it.py
configs/cloudformation/network.py
configs/cloudformation/stacks.yml
configs/cloudformation/utils.py

The IT template really only has to create the security group -- the instance itself isn't cloudy enough to be managed by CloudFormation.
One important bit of security group creation is referencing the VPC to which the SG belongs.  So I built out a bit of support for inter-stack references.  From what I can tell, the best practice for this is to feed such external resource IDs to CloudFormation manually via template parameters.  This is almost the same thing -- I've replaced "manually" with a handy-dandy lookup function, and replaced parameters with the much simpler pyplates feature, "options", which just substitutes the value directly into the template.
@davecurado, what do you think?  The missing piece here is that the SG is configured with a list of raw IPs, much of which will need to …

Add "IT" SG template

---

ami_configs/centos-65-x86_64-hvm-base.json
ami_configs/centos-65-x86_64-hvm-base/additional_packages
ami_configs/centos-65-x86_64-hvm-base/groupinstall
cloudtools/aws/instance.py
cloudtools/scripts/aws_create_ami.py
configs/server-linux64
configs/server-linux64.cloud-init
instance_data/us-east-1.instance_data_server_linux64.json
instance_data/us-west-1.instance_data_server_linux64.json
instance_data/us-west-2.instance_data_server_linux64.json

I suspect that this will work for buildbot masters, too, but that's out of scope here.  This did successfully rebuild rpmpackager1.
It's well broken out into commits to describe each step.

Bug 1129958: create a means of building CentOS-6.5 servers

---

configs/buildbot-master
configs/buildbot-master.cloud-init

Note, in particular, that this is based on the CentOS-6.5 hvm-base AMI with only Core installed, so these installs all pulled in what packages they needed without the benefit of the Base group, but that seems to work fine.  Updates in bug 1130548.

Bug 1130176: the config I built the new masters with

---

ami_configs/centos-65-x86_64-hvm-base/additional_packages
ami_configs/centos-65-x86_64-hvm-base/groupinstall
cloudtools/scripts/aws_create_ami.py
configs/bld-linux64
configs/buildbot-master
configs/try-linux64

I'm in the process of testing this for buildbot masters, and will create a canary for builders tomorrow before landing it.

Bug 1130548: update the base AMIs to work for both servers and builders

---

configs/cloudformation/network.py
configs/routingtables.yml

routingtables.yml no longer manages usw1, so this removes the config for
that region.

Reflect papertrail routes into CloudFormation template

---

cloudtools/aws/sanity.py
cloudtools/scripts/aws_sanity_checker.py

This fixes the time-based sorting on the aws_sanity_checker report.

In sanity report, use timestamp for sorting rather than formatted time.

---

cloudtools/aws/__init__.py
cloudtools/aws/instance.py
cloudtools/scripts/aws_create_instance.py
cloudtools/scripts/aws_watch_pending.py
configs/bld-linux64.cloud-init
configs/buildbot-master.cloud-init
configs/server-linux64.cloud-init
configs/tst-linux64.cloud-init

We need to overwrite Puppet generated rsyslog configs based on region. Golden AMIs are copied across regions (to keep them identical), so they have the same syslog server set.
This patch adds rsyslog section into cloud-init files. Also need to convert AWS region names to Moz region names. :)

Bug 1124313 - centralized logging

---

configs/securitygroups.yml

Aws-manager2 couldn't contact my new puppet master because the SG didn't allow it.  I've already deployed this change so that project could continue.

Add aws-manager* to all security groups to support creating new instances

---

cloudtools/scripts/aws_create_instance.py

The output log is sent with the periodic email. To make emails more actionable, we should report that a NetworkError has just happened (it always happens when we try to connect, for the first time to the new instance). Just log the error message, instead of the full "exc_info"

updated log message in create_instance in case of a NetworkError

---

configs/watch_pending.cfg

These builds are a different variant based on graphene. Since they'll be running on AWS instances, watch pending should know about them.

Bug 1160717 - let watch pending know about horizon builds

---

configs/securitygroups.yml

Instead of having a separate security group for windows to allow RDP and VNC, just properly adding them to the correct existing security groups should give them full access from the admin hosts.
Rail, is this the proper syntax to add additional tags that this sg should apply to?

bug 1173786; modify security groups for windows

---

cloudtools/aws/ami.py
configs/b-2008
configs/b-2008.cmd.user_data
configs/try-2008
configs/try-2008.cmd.user_data

These changes introduce 2 machine and userdata configs for windows 2008 build and try golden images. cloudtools/aws/ami.py was also modified to remove unix path cleanup which is not applicable on windows.

bug 1166448 - support golden ami creation for win 2008 bld/try

---

configs/b-2008
configs/try-2008

This PR addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1173786, by removing security groups: sg-18a07677 and sg-84beade6. There was some whitespace tyding required in the same files.

Bug 1173786: removed security groups sg-18a07677 and sg-84beade6

---

cloudtools/scripts/aws_watch_pending.py

I missed a token during earlier refactoring for https://github.com/mozilla/build-cloud-tools/pull/96

Bug: 1192234: reinstated token: moz_instance_type

---

cloudtools/aws/instance.py
configs/b-2008.user-data

Removed `instance.modify_attribute("userData", None) ` from instance.py which was causing ec2config to override the userdata persistence setting.
Also, added a check to userdata powershell to monitor and correct the setting if needed on each run.

Bug 1191717: leave win userdata intact during ami capture (assimilate_windows)

---

cloudtools/scripts/aws_watch_pending.py

Windows spot instances are being labelled and instantiated as Linux in the EC2 console. This doesn't affect the instance running correctly, but might be affecting our spot bid success rate.
This PR corrects the product_description argument in cloud-tools for Windows spot instance requests.

Bug 1192779: differentiate between platforms in spot requests

---

cloudtools/scripts/aws_watch_pending.py

We still haven't seen any y-2008 spot instances spin up. One change that was made around the time we stopped getting spin ups was https://github.com/mozilla/build-cloud-tools/pull/100 which was an effort to correctly label the product_description (platform) in EC2 as "Windows (Amazon VPC)" instead of "Linux/UNIX (Amazon VPC)". We need to experiment with reverting this change to see if it is what caused the lack of y-2008 spot spin ups.
https://bugzilla.mozilla.org/show_bug.cgi?id=1191717#c8

Revert product_description back to Linux

---

cloudtools/aws/sanity.py

Looks like just an old typo, but leaves misleading logs in papertrail.

unknown_type_message corrected to show mis-configured type

---

cloudtools/scripts/aws_create_instance.py

Windows spot instantiation is failing at this step with:
2015-08-18 07:36:20,226 - Spot request for y-2008-spot-001.try.releng.use1.mozilla.com (0.4)
2015-08-18 07:36:20,227 - Cannot start
Traceback (most recent call last):
File "aws_watch_pending.py", line 266, in do_request_spot_instances
is_spot=True, dryrun=dryrun, all_instances=all_instances)
File "aws_watch_pending.py", line 320, in do_request_instance
"region_dns_atom": get_region_dns_atom(region)})
File "/builds/aws_manager/cloud-tools/cloudtools/aws/instance.py", line 311, in user_data_from_template
user_data = user_data.format(**tokens)
KeyError: 'puppet_server'
This PR will hopefully fix this issue.

Bug 1191717: set puppet server; r=rail

---

configs/b-2008.user-data

Still getting errors in aws_watch_pending.log related to the {puppet_server} token. removing it from powershell, to see if this prevents the exception.

disable token temporarily

---

cloudtools/scripts/aws_watch_pending.py

Now that Windows spot instances are working again, retry setting the product description to the correct platform.

Bug 1192779: reinstate Windows product_description

---

configs/watch_pending.cfg

Watch pending is failing to instantiate y-2008 spot instances due to the pricing rules. This is a temporary max bid increase to enable us to get on with testing for https://bugzilla.mozilla.org/show_bug.cgi?id=1198317
2015-08-26 23:06:01,897 - getting all spot requests for us-east-1
2015-08-26 23:06:07,692 - 0 active spot requests for us-east-1 y-2008
2015-08-26 23:06:07,697 - 0 real active spot requests for us-east-1 y-2008
2015-08-26 23:06:07,992 - Sanity checking c3.2xlarge in us-west-2a
2015-08-26 23:06:07,992 - Price is higher than 80% of ours, c3.2xlarge (us-west-2, us-west-2a) 0.3961 (value: 0.3961) < 0.4
2015-08-26 23:06:07,993 - Skipping c3.2xlarge (us-west-2, us-west-2a) 0.3961 (value: 0.3961) < 0.4 for us-west-2 - unusable
2015-08-26 23:06:07,993 - Sanity checking c3.2xlarge in …

Bug 1198317: increase max bid for y-2008 instances

---

configs/Ec2UserdataUtils.psm1
configs/b-2008.user-data

This PR updates 2008 userdata powershell to disable windows updates if the instance has them enabled. Additionally, Ec2UserdataUtils.psm1 was not source controlled (just hosted at http://releng-puppet2.srv.releng.scl3.mozilla.com/repos/powershell/Ec2UserdataUtils.psm1). I have included it here so that we can track changes.

Bug 1195880: disable windows update at boot, if enabled

---

configs/watch_pending.cfg

following an irc conversation with @rail, set a more sensible max bid for Windows 2008 c3.2xlarge

bump up max bid for (b|y)-2008

---

configs/Ec2UserdataUtils.psm1
configs/b-2008.user-data

Further to conversations in #specops, we need to experiment with disabling the Windows firewall to determine if it is causing the hg clone failures.

Bug 1199267: disable windows firewall (rely on ec2 Security Groups)

---

configs/routingtables.yml

* for compile products
* builders can talk to prod and stage hosts, so we can test in staging
* non-try to non-try, and try to try only
* for log upload from masters
* us-west-2 masters only get prod hosts
* us-east-1 master can also talk to stage, to test uploads from dev-master2.bb.releng.use1

Add new hosts to routing config.

---

configs/Ec2UserdataUtils.psm1

we get a couple of frequent exceptions in ec2config logs. this pr addresses this by introducing a check for the existence of a registry key before attempting to delete it and a correction to an xml property setter.

check for reg key before delete attempt and fix xml hostname update

---

configs/Ec2UserdataUtils.psm1
configs/b-2008.user-data

there is a lot of noise in the event log from the parent (golden/base) amis. this pr adds a purge step to the ami capture to discard this noise before generating clean amis.

Bug 1205640: purge event log before golden ami capture

---

configs/dev-linux64

This will create second EBS disk, which can be added to LVM using following commands:
```bash
pvcreate /dev/xvdb
vgextend cloud_root /dev/xvdb
lvextend -l 100%VG /dev/cloud_root/lv_root
resize2fs /dev/cloud_root/lv_root
```

Use second disk for dev build isntances

---

configs/securitygroups.yml

The idea is to restrict flows to the internet using security groups;
flows to other mozilla destinations (10.0.0.0/8) are always filtered
at the destination.  This is based on the flows explicitly allowed to
datacenter hosts, per the firewall tests.

Bug 1210137: restrict outbound flows from AWS

---

configs/watch_pending.cfg

As rail and I discussed today. 2xlarge will result in 160G of ephemeral storage, and more for the 4xlarge and 8xlarge, so we'll have enough space to download a full set of release builds. Swap to ondemand to not worry about getting outbid.

Bug 1145774, Use 2xlarge or bigger instances for av scans, and swap to ondemand

---

configs/b-2008.user-data

reboot logic before was causing spot boot-loops. this pr moves the spot reboot logic back inside the host rename logic.

bug 1199267: always shutdown golden, only reboot spot on hostname change

---

configs/Ec2UserdataUtils.psm1
configs/b-2008.user-data

Add support for windows loaner instances in ec2 by:
- removing the contents of c:\users\cltbld\.ssh
- removing the contents of c:\builds (tokens, oauth keys, etc)
- secure wipe of free space on C: drive
- generating a new random password for root, cltbld and the local vnc server 
- patches broken ini value update
- prevent auto login of cltbld

Bug 1226662: Prep windows loaner instances

---

configs/watch_pending.cfg

- set spot bid for g2.2xlarge to $1.00 (based on 3 month historical prices for instance type)
- match win spot instance limits with slave-alloc counts (limits set with slave-alloc enable/disable)

Bug 1223509

---

ami_configs/releng-public-precise.list
configs/tst-emulator64
configs/tst-linux32
configs/tst-linux64

Bug 1220658 - Upgrade ec2 test instances mesa versions to mesa-lts-saucy-9.2.1
Regenerated base AMIs with precise-updates enabled

Update ubuntu amis

---

configs/b-2008.user-data

this pr fixes a userdata issue where bundleclone falls back to us-east-1 when no domain info is supplied in userdata. the patch corrects this by providing the missing parameter.

Bug 1232501: set missing domain parameter for bundleclone; r=markco

---

cloudtools/scripts/aws_watch_pending.py

this was originally part of another PR (https://github.com/mozilla/build-cloud-tools/pull/158) for 2008 but is needed now to allow spot instantiation of t-w732.

unblock t-w732 spot instantiation

---

cloudtools/scripts/aws_publish_amis.py

https://s3.amazonaws.com/mozilla-releng-amis/amis.json is very hard to read in Firefox, and adding an extension like JSONView doesn't help because it only enables for the Content-Type of application/json. So this would fix it up, but I'm not sure what's consuming the file now and if it's going to care about the header changing from text/plain.

Set correct Content-Type for amis.json

---

configs/Ec2UserdataUtils.psm1

This PR updates the hg cache creation mechanism to correct the default path (in hgrc) for the try repository which is created from hg.m.o/m-c (rather than try)

Bug 1245008: change default path of try repo cache from m-c to try

---

configs/Ec2UserdataUtils.psm1

After discovering that we can have issues which create some but not all certs, this pr patches userdata to delete any old certs. In the past it would only delete certs if all of them existed.

Bug 1246397: Handle scenarios where not all keys are present

---

configs/Ec2UserdataUtils.psm1
configs/b-2008.user-data

This PR retries puppet cert downloading indefinitely until the instance is manually terminated or a cert is successfully installed. An engineer can fix the cert propagation problems and just wait for the golden instance to notice.
If cert installation succeeds, we move to the puppet agent run and repeat until C:\ProgramData\PuppetLabs\puppet\var\state\last_run_summary.yaml exists and contains both terms: "failed: 0" (indicates a resource failed to install) and "failure: 0" (indicates a failure event occurred). See https://puppetlabs.com/blog/puppet-monitoring-how-to-monitor-the-success-or-failure-of-puppet-runs for rationale. An engineer can push patches to puppetagain, until the golden instance produces a successful agent run.
The wait period between retries (for either cert or agent …

Bug 1246397: loop indefinitely on puppet cert download failures

---

configs/subnets.yml
configs/watch_pending.cfg

The changes have been tested locally without any issue

Bug1252248 - Add more tst-linux64, tst-emulator64 capacity in AWS

---

cloudtools/aws/spot.py

…of AWS instances, eg bad golden ami and reverting to previous.
I think this should do the trick. All alternative would be filter at https://github.com/mozilla/build-cloud-tools/blob/master/cloudtools/scripts/aws_watch_pending.py#L446, but that's used in many places and I'm unsure if there would be any fallout.

Bug 1249527 - Investigate quicker recovery from mass-termination

---

configs/routingtables.yml

... to the configs for testers. I'd like to do something that uses https://ip-ranges.amazonaws.com/ip-ranges.json in the long term but this is the short term fix.

Add current Cloudfront block for public-artifacts.taskcluster.net

---

configs/watch_pending.cfg

The new builder names are:
Firefox try linux l10n
Firefox try linux64 l10n
Firefox try macosx64 l10n
Firefox try win32 l10n
Firefox try win64 l10n

Watch for pending desktop l10n on try

---

cloudtools/scripts/aws_watch_pending.py

At some point we switched from using Windows instances in AWS to using
Linux instances, but neglected to update the product description. This
meant we were looking at Windows spot price history to find the
cheapest region, and then requesting Linux instances in those regions.

Bug 1281199 - Fix product type when requesting spot prices

---

configs/Ec2UserdataUtils.psm1

The `Disable-Service -serviceName 'puppet'` line here should stop and disable the running puppet service. For golden runs we use the puppet agent cli rather than the service, so there's no good reason for it to be running.
The `Remove-ItemProperty -Name 'fPromptForPassword' -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services'` line is a piggyback change to change the rdp service behaviour to allow rdp clients to authenticate from the command line (as all our other windows instances allow)

bug 1286549 - disable puppet service (t-w732); r=markco

---

configs/Ec2UserdataUtils.psm1
configs/b-2008.user-data

- puppet updates hg to a version which supports clonebundle so we wait for that to be available before cloning caches
- previously the decision to create caches relied on "ec2" existing in the hostname, now its just inside the explicit `Prep-Golden` and `Prep-Loaner` methods. less ambiguous logic
- there was a bunch of logic for configuring bundleclone. i replaced that with clonebundle configuration.
- i opted to put the clonebundle config into mercurial.ini (rather than a --config arg to hg) so that we can include the correct ec2 region
- the unused (deprecated) method `Run-BuildBot` referenced the changed method `Enable-BundleClone` so i opted to just remove the unused method rather than correct it
- we no longer differentiate between try and build caches so i removed logic that used to …

create hg caches after puppet run

---

configs/b-2008
configs/watch_pending.cfg
configs/y-2008

Updated builder instance type  to c4 for cost savings and to help congestion

Update instance type for windows builders to c4

---

configs/Ec2UserdataUtils.psm1

This PR addresses the requirement to use nsis 3.0b3 instead of 3.0b1 on Windows buildbot builders. It does this by:
- moving the current mozilla-build folder from c:\mozilla-build to c:\mozilla-build-1.9.0
- creating a symlink at c:\mozilla-build pointing to c:\mozilla-build-1.9.0
- installing mozilla-build 2.2.0 to c:\mozilla-build-2.2.0
- creating a symlink at c:\mozilla-build\nsis-3.0b3 pointing to c:\mozilla-build-2.2.0\nsis-3.0b3
- replacing the env PATH entry for nsis-3.0b1 with one for nsis-3.0b3
This approach has several extra advantages:
- Future requests for access to mozilla-build components newer than 1.9.0 are easy to accommodate.
- Installation of future versions of mozilla-build can be achieved by changing the -version parameter to the installation method.
- It leaves the …

bug 1236624 - install mozilla-build 2.2.0 alongside 1.9.0 and use nsis 3.0b3

---

cloudtools/aws/spot.py
cloudtools/scripts/aws_watch_pending.py

By the use of the following tricks:
* asking for specific instance types
* only paying attention to the availability zones we'll use
* making small requests, and bailing out as soon as we have all prices needed
The treat is dropping price fetch time from ~10 minutes to 20 seconds. That's on my laptop with NZ-style latency, while on aws-manager2 we typically take about 5 minutes.

Bug 1302569 - Speed up spot price fetching

---

cloudtools/graphite.py
cloudtools/scripts/aws_check_subnets.py
cloudtools/scripts/aws_clean_log_dir.py
cloudtools/scripts/aws_create_ami.py
cloudtools/scripts/aws_create_instance.py
cloudtools/scripts/aws_create_win_ami.py
cloudtools/scripts/aws_deploy_stack.py
cloudtools/scripts/aws_get_cloudtrail_logs.py
cloudtools/scripts/aws_manage_instances.py
cloudtools/scripts/aws_manage_routingtables.py
cloudtools/scripts/aws_process_cloudtrail_logs.py
cloudtools/scripts/aws_publish_amis.py
cloudtools/scripts/aws_sanity_checker.py
cloudtools/scripts/aws_stop_idle.py
cloudtools/scripts/aws_terminate_by_ami_id.py
cloudtools/scripts/aws_watch_pending.py
cloudtools/scripts/copy_ami.py
cloudtools/scripts/ec22ip.py
cloudtools/scripts/free_ips.py
cloudtools/scripts/get_spot_amis.py
cloudtools/scripts/spot_sanity_check.py
cloudtools/scripts/tag_spot_instances.py
configs/cloudformation/network.py

flake8 v3.2.0 complains when you don't have two empty lines after class and function definitions, eg
```
py27 runtests: commands[0] | flake8
./cloudtools/graphite.py:62:1: E305 expected 2 blank lines after class or function definition, found 1
_graphite_logger = GraphiteLogger()
^
./cloudtools/scripts/aws_check_subnets.py:128:1: E305 expected 2 blank lines after class or function definition, found 1
if __name__ == '__main__':
^
```
Change log is at http://flake8.pycqa.org/en/latest/release-notes/3.2.0.html

Fix flake8 complaints

---

configs/watch_pending.cfg

Because we have many releases in flight and need to make sure instances spin up for buildbot-based jobs.

Add linux and windows builders for l10n repack and update verify

---

configs/b-2008
configs/y-2008

The old installation of HG was causing intermittent timeouts of the install of the new version of HG.

Bug 1331636 Remove old installation of HG

---

terraform/cache.mozilla-releng.net/backend.tf
terraform/cache.mozilla-releng.net/initialize.tf
terraform/cache.mozilla-releng.net/main.tf
terraform/cache.mozilla-releng.net/provider.tf
terraform/cache.mozilla-releng.net/resources.tf
terraform/cache.mozilla-releng.net/terraform.tfvars
terraform/cache.mozilla-releng.net/variables.tf

This commit provides the necessary terraform configs to
create a cloudfront distribution for cache.mozilla-releng.net.
It also creates the s3 bucket backend and a route53 A record.

Bug 1344412: Configure cache cloudfront distrobution in Terraform

---

terraform/base/route53.tf

This simply adds in the shipit cnames for the new shipit heroku apps.  It has already been applied via terraform.  This just needs to be merged to match reality.

Bug 1357837: add shipit cnames to terraform

---

configs/depsigning-worker
configs/depsigning-worker.user-data

depsigning [script]workers can spin up without any special config. Let's automate that via cloud tools!
I'm still holding off on standard signing scriptworkers because they require gpg keypairs in hiera... not sure if that's a great reason.

bug 1379653 - create depsigning workers

---

configs/securitygroups.yml

@AlinSelagea is this the modification needed for the security policies for https://bugzilla.mozilla.org/show_bug.cgi?id=1359389 ? It sounds like we've removed influxdb entirely, and so I removed the definition and uses.

bug 1359389 - securitygroups remove influxdb

---

configs/securitygroups.yml

This is the same set of access as beetmover has.

Bug 1380548 - add a security group for binarytransparencyworker

---

cloudtools/scripts/aws_manage_securitygroups.py

`conn` is a connection to one of the regions in the config (see line 232 of this file) and may not match the region where we created a new sec group. Explicitly using the connection for the same region avoids the failure to look up the group (due to longer propagation delays than we allow for).
Also logs the id of the new sec group to avoid having to go to the console to find it.

Bug 1166064 - fix creation of new security groups

---

terraform/base/route53.tf

This modifies the route53 terraform config in order to move a few heroku app cnames to non-sni endpoints.  State has already been applied.

Bug 1380177 - [terraform] move route53 records to new ssl endpoints

---

terraform/base/route53.tf

This commit removes the interation being used to generate cname
record resources for bunch of heroku apps.  I've run into issues
where making a single change to the cname array causes all the
resources generated from that list to be destroyed and
recreated.  That isn't good so I'm opting to not be cleaver and
instead expicitly call out all cnames as independent resources.
The other problem this should elminate is having to run
terraform apply multiple times in order to reach final state.

[terraform] unwind route53 records

---

configs/securitygroups.yml

I've added the releng jumphost hostnames to securitygroups.
@dividehex could you review and merge this? Will the change be applied automatically, or do I need to ask build-duty (or run it myself on aws-manager)?

Bug 1392800 - Add releng jumphosts to admin_access in securitygroups

---

.travis.yml
cloudtools/scripts/aws_manage_routingtables.py
configs/routingtables.yml
configs/subnets.yml
setup.py

This is the bulk of the new code
* setting up a new 'public' subnet in each region for the NAT gateway to reside in, and a routing table that sends outbound traffic from the NAT to the IGW
* support to look up the NAT gateway, which we reluctantly do using boto3 because boto doesn't support them
* use the gateway for staging upload hosts for testing porpoises
Setup of the one NAT gateway per region is manual, once the subnets exist and EIPs are allocated.
After this lands is
* almost-production testing that NAT gateway is working for staging hosts
* verify network ACL situation (no external access to NAT, maybe lock down NAT subnet to master + build subnets)
and then
* swing production traffic over to NAT gateway and verify log and build uploads OK
* ask CloudOps to whitelist IPs on prod …

Bug 1361930 - support for NAT gateways, swing traffic for staging uploads that way

---

configs/Ec2UserdataUtils.psm1

I took the liberty of removing both clonebundle and bundleclone since neither of these methods are used any longer and their existence may cause confusion since puppet handles the hg configuration for these instances.

Bug 1359264 - remove unused clonebundle and bundleclone references

---

configs/securitygroups.yml

(Collaborative effort of @davehouse and @dividehex) 
This PR is part of an overall Q3 OKR to implement host-based fire-walling with the ultimate intent to limit administrative access (ssh, rdp, vnc) to jumphost duo auth'ed traffic only.   Below is a bullet point summary of things:
- Remove Observium.  AFIAK, this is not used by netops any longer and shouldn't be allowed to touch snmp on the ec2 hosts.  We also shouldn't be running snmp on any ec2 hosts.  I've checked with #moc and they show no record of needing it since the monitor that on the scl3 net equipment already.  HT to @hwine and @fauweh for info on this.
- Refined admin access: currently, admin access allows ANY protocol on ANY port from a wide range of admin hosts, nagios, vpn ip, etc.  This removes all of that and replaces it …

Security group audit

---

configs/securitygroups.yml

@dividehex The universal is included in other lists and the yaml include does not flatten the tree. So ~~let's remove the list wrapping the children of universal. Universal is only included, when included it will always be dropped into place as list elements instead of an element which is a list.~~ let's not use the universal in places where there are in-line rules defined, but only use it when it is the only include.

fix securitygroups include of universal

---

configs/routingtables.yml

Swings master, build and try pool traffic over to the NAT gateways.

Use NAT for production uploads

---

configs/securitygroups.yml

See bug 1451957.   MDC2 needs to be included for allowing inbound puppet and rejh traffic

Bug 1451957: include mdc2 cidr in sg config

---

instance_data/instance_data_generic.json
instance_data/us-east-1.instance_data_dev.json
instance_data/us-east-1.instance_data_master.json
instance_data/us-east-1.instance_data_prod.json
instance_data/us-east-1.instance_data_server_linux64.json
instance_data/us-east-1.instance_data_tests.json
instance_data/us-east-1.instance_data_try.json
instance_data/us-west-1.instance_data_server_linux64.json
instance_data/us-west-2.instance_data_server_linux64.json

This commit updates all the instance data files to include mdc1
and mdc2 puppetmasters while removing the scl3 puppetmasters.
The scl3 puppetmasters will die soon along with scl3 itself.
This also changes the dev puppet master to point the
releng-puppet2.srv.releng.mdc1 which means users will need to
begin using that host for their puppet dev environments.  That
host will also be promoted to the distinguised puppetmaster very
soon.

Bug 1444467: update instance data files with mdc1/mdc2 puppetmasters

---

configs/watch_pending.cfg

(releaseduty triggers esr52 linux builds to unblock thunderbird releases)

stop triggering linux esr52 builds for thunderbird

---

setup.py

Over in https://bugzilla.mozilla.org/show_bug.cgi?id=1450035 we bumped the pyyaml version on aws_manager (to match what was available on the Puppet servers). It looks like cloud tools and puppet are fighting a battle over which version to keep installed -- let's update this one to match what's in Puppet.

Bump pyyaml version.

---

terraform/base/route53.tf

I'm working for Release Management, building a new code coverage service on [mozilla-releng/services](https://github.com/mozilla-releng/services/) with @marco-c.
We got a new domain name **moz.tools** registered, and would like to use its subdomains for our 3  Heroku instances :
* `coverage.moz.tools`
* `coverage.staging.moz.tools`
* `coverage.testing.moz.tools` 
Could you also give me the Route53 server used to finish the DNS setup. Thanks !
Ping @dividehex, as specified on the [documentation](https://docs.mozilla-releng.net/deploy/configure-dns.html)

Add moz.tools and code coverage backend DNS

---

terraform/base/route53.tf

As mentioned #312 I finally managed to get a generated configuration done.
Problem we are trying to solve/avoid is that with growing number of services it is hard to keep track what is deployed to production and/or staging.
For this reason we added new subcomand to ./please command that generates route53 configuration, since what is deployed where is already stored alongside with our code.
```console
$ ./please tools terraform-route53-config
```
This commit adds projects on testing channel (*.testing.mozilla-releng.net, *.testing.moz.tools) and removes projects not deployed to existing channels.
Projects removed:
- "heroku-archiver-cname-prod"
- "heroku-clobberer-cname-prod"
- "heroku-mapper-cname-prod"
- "heroku-dashboard-shipit-cname-prod"
- "heroku-dashboard-shipit-cname-stage"
- …

Generated route53.tf config for mozilla-releng/services websites

---

terraform/base/route53.tf

This PR adds 3 new subdomains to the `moz.tools` domain, to expose a new [Javascript frontend](https://github.com/mozilla/release-services/pull/1340), served from Cloudfront.
The [S3 buckets](https://github.com/mozilla/release-services/pull/1340#issuecomment-410680523) have been created by @garbas 
I'm not sure about the `zone_id` on line 449, could you have a look @dividehex ? Thanks !

Add routes for static-analysis.moz.tools hosted on Cloudfront

---

terraform/vpns/backend.tf
terraform/vpns/initialize.tf
terraform/vpns/provider.tf
terraform/vpns/resources.tf
terraform/vpns/terraform.tfvars
terraform/vpns/use1.tf
terraform/vpns/usw1.tf
terraform/vpns/usw2.tf
terraform/vpns/variables.tf

This setups a new terraform config and state for managing the
releng vpn connections between the aws regions (use1, usw2, and
usw1) and the mozilla datacenters (mdc1 and mdc2).  This
creates a new UNATTACHED vpn gateway, imports the existing
mdc1/2 customer gateways and builds new connections.  It does
not manage the current vpn gateway nor its connections.  This
will allows us to cut over by detaching the old vpn gateway and
attaching the new one.

Bug 1480861: Setup new VPNs between AWS and MDC1/2

---

tox.ini

travis ci is failing because of pytest-cov's req for coverage to be a higher version than we have pinned. However, it looks like args/other change for newer py-test. So let's pin to the expected version <2.6

fix deps for tox on travis

---

terraform/base/route53.tf

These changes remove cnames of applications that have been deleted and update the cnames of applications that have been moved to heroku's ACM.  As a note, herokussl.com subdomains point to elbs associated with the ssl endpoint addon while herokudns.com points at heroku's ACM managed ssl endpoints.
All of these changes only affect staging and testing heroku apps.  I'm leaving the production apps for next week.

Terraform route53 changes

---

terraform/base/route53.tf

Treestatus production was moved to the heroku acm and therefore has a new ssl endpoint.

Bug 1487798: change production treestatus cname

---

terraform/base/route53.tf

Tooltool endpoint ssl has been changed to heroku's ACM.  Cname is now changed to point there.

Bug 1487798: change production tooltool cname

---

terraform/base/route53.tf

This changes the cname of the production coalesce application ssl enpoint now that the app is configured to use Heroku's ACM.  It also adds a cname for the coalesce staging app which didn't exist for some reason.

Change coalesce cnames

---

terraform/base/route53.tf

As requested on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1505154#c5)
@garbas @dividehex How can i get an ssl certificate for this domain without using let's encrypt ?

Add CNAME for buildhub.moz.tools

---

terraform/base/route53.tf

This is needed to publish Release Management event listener project, used by Harbormaster & code review bot.

Add eventlistener DNS records

---

terraform/base/route53.tf

Reverts mozilla-releng/build-cloud-tools#379, caused https://bugzilla.mozilla.org/show_bug.cgi?id=1546380

Revert "terraform: move static pages to cloudops managed S3 buckets"

---

terraform/base/route53.tf

There should have always been a '.' in the moztools hosted zone name but I think terraform is now either not adding.  Therefore without it, terraform wants to deletet the zone and recreate it.

Add root . to moztools hosted zone name

---

terraform/base/route53.tf

I'm moving code-coverage applications to a new [Github repository](https://github.com/mozilla/code-coverage) & new Heroku instances.
We are also removing the staging instance (no need anymore), and updating the domain name to :
* `api.coverage.moz.tools` for production
* `api.coverage.testing.moz.tools` for testing

Update codecoverage Heroku DNS

---

terraform/base/route53.tf

This PR brings under the same domain `code-review.moz.tools` the 3 parts of [code-review bot](https://github.com/mozilla/code-review):
1. eventlistener.moz.tools events.code-review.moz.tools (same for testing)
2. the eventlistener.moz.tools domains are preserved until we update the Phabricator usage
3. the new code-review backend is exposed as api.code-review.moz.tools (same for testing)
4. the static-analysis frontend is directly renamed as code-review.moz.tools (same for testing)
All staging environments are not used anymore for code-review.

Unify code-review domain names

---

terraform/base/route53.tf

As I cannot update (nor releng this week) the cloudfront configuration for the code-review frontend, let's revert the DNS changes for the code-review frontend.
Could you please merge & apply these changes @dividehex ?

Revert code-review.moz.tools frontend DNS to static-analysis.moz.tools
