mozilla-releng/build-cloud-tools

scripts/aws_sanity_checker.py
This will also terminate instances not tagged properly
=> Better spot instance detection

configs/cloudformation/network.py, setup.py
Changes I made while deploying into usw1
=> Bug116271 deploymen

cloudtools/scripts/aws_deploy_stack.py
If I didn't need more evidence that I should have better tests, I do now :(
=> Fix tailing logs on --delete

configs/securitygroups.yml
I missed this one in 2d570391c7ef25d6661903144db13434544ddf1b
=> Bug 1130540: add the other flow for aws-manager2

configs/cloudformation/network.py
=> mirror 5e558b0 into cloudformation

configs/routingtables.yml
needed for centralized logging
=> Bug 1122053: add internet routes for log hosts; r=dustin

configs/watch_pending.cfg
This is probably why my Graphene job isn't starting!
=> Add graphene builder to bld-linux64 start list.

configs/securitygroups.yml
Thanks, firewall-tests, for finding this ;)
=> dev-master1 is gone

configs/watch_pending.cfg
Add more tst-linux64 machines (+200 per region)
=> Bug 1143901 - Add more capacity in AWS for tests (tst-linux64-spot) 

cloudtools/aws/ami.py, cloudtools/scripts/aws_watch_pending.py
This is just to test the waters. The changes here only impact spot requests. Moving the changes to on-demand instances will require a good deal more refactoring.
=> Slow rollouts

instance_data/us-east-1.instance_data_prod.json, instance_data/us-east-1.instance_data_try.json
I think we don't use gaia-central anymore.
=> Do not pre-populate gaia-central mercurial repos

instance_data/us-east-1.instance_data_try.json
=> Use smaller git shared tarball for try

configs/cloudformation/archiver.py, configs/cloudformation/iam_relengapi.py, configs/cloudformation/stacks.yml
this adds the already r+ commits plus a stacks yml update so I can deploy changes.
once landed, my plan is to hop on aws-manager2 as buildduty at /builds/aws_manager/cloud-tools/scripts and run the following (in order):
./aws_deploy_stack.py ArchiverUsw2
./aws_deploy_stack.py ArchiverUse1
./aws_deploy_stack.py IAMRelengAPI   # to re-deploy changes I did here
./aws_deploy_stack.py IAMRelengAPIStaging
=> Archiver iam relengapi

cloudtools/slavealloc.py, configs/watch_pending.cfg
Amy requested that I merge these changes from her fork. Some context at: https://bugzilla.mozilla.org/show_bug.cgi?id=1166448
=> updated the instance types to be c3.2xlarge and adjusted the price

configs/Ec2UserdataUtils.psm1
I screwed up in my last commit. 'else if' isn't valid powershell syntax. This pr corrects my error and *is* properly tested.
=> syntax correction

configs/securitygroups.yml
Testing on a few nodes was successful - let's ship it!
=> Bug 1210137: restrict outbound from slave VLANs

configs/Ec2UserdataUtils.psm1, configs/b-2008, configs/b-2008.user-data, configs/y-2008
This PR references temporary hand built b-2008 and y-2008 amis which are preconfigured as build and try buildbot Windows slaves. Userdata for these moz-types has also been updated to accommodate the ami configuration
=> Bug 1199267: Temporary 2008 AMIs

configs/b-2008.user-data
just a correction to an earlier error
=> only reboot if hostname has changed

configs/Ec2UserdataUtils.psm1, configs/b-2008.user-data, configs/y-2008
This PR contains updated y-2008 AMIs which include a pre-cloned hg-shared/try repository
=> new y-2008 amis

configs/Ec2UserdataUtils.psm1
the cached repos were producing build failures. not sure why yet, but removed to get green builds back
=> reverted clone of inbound (b) and try (y)

configs/Ec2UserdataUtils.psm1, configs/b-2008, configs/b-2008.user-data
Also corrects userdata to populate caches based on intended hostname rather than current hostname
=> Bug 1222556: new base amis for b-2008

configs/Ec2UserdataUtils.psm1
should reduce build times for a few common prod builders
=> more hg caching on golden: m-c, fx-team, ux

configs/routingtables.yml, configs/securitygroups.yml
=> Bug 1242014 - Support routing for seabld productdelivery upload host

configs/Ec2UserdataUtils.psm1
this pr fixes an issue on 2008 base amis where some scheduled task files are missing their .xml extensions
=> fix invalid scheduled task filenames

configs/Ec2UserdataUtils.psm1
Our puppet agent success/failure check included a parse of the puppet-agent-summary (https://groups.google.com/a/mozilla.com/forum/?hl=en#!topic/releng-puppet-mail/NMXCqTpLM5k) log but not the puppet-agent-run log (https://groups.google.com/a/mozilla.com/forum/?hl=en#!topic/releng-puppet-mail/mOroIr9m-MQ) where today's failures were recorded.
This PR addresses this by parsing for a specific failure message in the agent run log as an additional mechanism for detecting a puppet agent run failure.
=> Bug 1255572: parse the puppet agent summary log for a failure message

configs/Ec2UserdataUtils.psm1
@grenade, as we discussed a while ago the UX repo is having a long lie down. r?
=> Remove UX branch as last commit was 2014-05

configs/Ec2UserdataUtils.psm1
See https://bugzilla.mozilla.org/show_bug.cgi?id=1261812
=> set win error reporting keys

configs/Ec2UserdataUtils.psm1
=> explicit error actions on path checks

configs/watch_pending.cfg
I reviewed the bad backout, so I fix the bad backout.
=> Fix broken backout

configs/watch_pending.cfg
This reverts commit 73678cc03e3d155c79e8ccf0195bfd01f5255f3d.
=> Revert "use m3.xlarge for t-w732 (#214)"

configs/t-w732
=> New AMI ids

cloudtools/aws/instance.py, instance_data/us-east-1.instance_data_prod.json, instance_data/us-east-1.instance_data_tests.json, instance_data/us-east-1.instance_data_try.json
There are still references to the old repos in configs/Ec2UserdataUtils.psm1. I'll handle that file in a separate PR.
=> Remove hg bundles

configs/Ec2UserdataUtils.psm1
I haven't tested this because I don't know how. I'm also not a PowerShell expert. I wouldn't be surprised if something broke horribly.
Also, before this is merged, please tell me when this code runs in production (e.g. how often it runs). I'm concerned about the load impact of changing this and don't want it to roll out before I understand when it runs.
=> Change Mercurial repo seeding on Windows

configs/b-2008.user-data
https://bugzilla.mozilla.org/show_bug.cgi?id=1287417
=> Bug 1287417 - pull ps module from github rather than puppet; r=Callek

cloudtools/scripts/aws_create_instance.py
Adding a sleep to allow Windows to catch up before a shutdown
=> Bug 1289875

configs/watch_pending.cfg
=> bump g-w732 g2.2xlarge bid price to 9.0

configs/Ec2UserdataUtils.psm1
Userdata was updated and repinning the mercurial.ini to on old fingerprint. Updated to the correct finger print.
=> Bug 1147548 update hg fingerpint

configs/balrogworker, configs/balrogworker.user-data, configs/securitygroups.yml, configs/subnets.yml
@rail r?
Am still confused with respect to some of the values there but hopefully the backbone is correct.
=> Bug 1306753 - first draft iteration on cloud tools configs. r=rail

configs/pushapkworker, configs/pushapkworker.user-data, configs/securitygroups.yml
@MihaiTabara pointed me to #256 and #259 as examples.
=> Bug 1307826 - Deploy PushApkWorker on its own production machine

configs/Ec2UserdataUtils.psm1, configs/b-2008, configs/b-2008.user-data, configs/y-2008
Bug  1307798 - 2008 ephemeral drive support
=> Bug 1307798

configs/b-2008, configs/watch_pending.cfg, configs/y-2008
This reverts commit 6701be330281924bf57fc387cc55b900aeec2a9b.
Reverting on suspicion that it's causing bug 1147271
=> Revert "changing instace type to c4.4xlarge for b-2008 and y-2008"

configs/bouncerworker, configs/bouncerworker.user-data, configs/securitygroups.yml
=> Bug 1433459 - Add bouncerworker instance type

configs/pushsnapworker, configs/pushsnapworker.user-data, configs/securitygroups.yml
=> Bug 1447263 - Add pushsnapworker instance type

configs/addonworker, configs/addonworker.user-data, configs/securitygroups.yml
=> Bug 1441353 - Add addonworker instance type

cloudtools/aws/instance.py, configs/Ec2UserdataUtils.psm1
Found these while poking around.
=> Switch hg references to git.

terraform/README.md
This adds some basic instructions for using terraform here.
=> Add readme file on using terraform

terraform/base/route53.tf
@dividehex Could you have a  look and apply this change ? Thanks !
Blocks [Bug 1545363](https://bugzilla.mozilla.org/show_bug.cgi?id=1545363#c29)
=> Add coverity.moz.tools CNAME record.

terraform/base/route53.tf
=> terraform: tooltool and treestatus move production to gcp

terraform/base/route53.tf
=> terraform: migrating mozilla-releng.net zone to cloudops

configs/securitygroups.yml
If there are any other modifications I need to make please let me know!
=> Bug 1495917 - Clean up of scl3 from securitygroups

terraform/base/route53.tf
This reverts commit c29fd10e257be8227c7194410fbd5c81d31f1aa1.
=> Revert "terraform: migrating mozilla-releng.net zone to cloudops (#386)"
